# Keep track of the face state

IDLE		= 'blink'
HAPPY		= 'happy'
SAD			= 'sad'
CRY			= 'cry'
SHOCK		= 'shock'
SLEEP		= 'sleep'
WINK		= 'wink'
CONFUSED	= 'confused'
SMIRK		= 'smirk'
DEAD		= 'dead'
ANGRY		= 'angry'
LAUGH		= 'laugh'
LOL			= 'lol'
BLUSH		= 'blush'
KISS		= 'kiss'
COOL		= 'cool'
WORRIED		= 'worried'
ANIME		= 'anime'
MONEY		= 'money'
CYLON		= 'cylon'
OWO			= 'owo'
LOOKING		= 'looking'
